import chalk from 'chalk';
import path from 'path';
import fs from 'fs';
import { markdownParser } from '../../../md.mjs';
import { logSuccess, logError, ensureDir, fileExists } from '../../../utils/helpers.js';

/**
 * 预览主题
 * @param {Command} command 
 * @param {Object} options 
 */
export async function run(command, options) {
  const themeName = command.args[0];
  
  if (!themeName) {
    logError('Please specify a theme name');
    console.log('Usage: md-beautify theme preview <theme-name> [-o output.html]');
    console.log('Use "md-beautify theme list" to see available themes');
    return;
  }
  
  const availableThemes = ['default', 'github', 'wechat', 'zhihu'];
  
  if (!availableThemes.includes(themeName)) {
    logError(`Theme "${themeName}" not found`);
    console.log('Available themes:', availableThemes.join(', '));
    return;
  }
  
  // 创建示例内容
  const sampleMarkdown = `# ${themeName.charAt(0).toUpperCase() + themeName.slice(1)} Theme Preview

This is a preview of the **${themeName}** theme.

## Features

- Beautiful typography
- Code syntax highlighting
- Responsive design
- Clean and modern layout

### Code Example

\`\`\`javascript
function hello(name) {
  console.log(\`Hello, \${name}!\`);
}

hello('World');
\`\`\`

### Lists

1. First item
2. Second item
   - Nested item
   - Another nested item
3. Third item

### Blockquote

> This is a blockquote example.
> It can span multiple lines.

### Table

| Feature | Description |
|---------|-------------|
| Theme | ${themeName} |
| Status | Preview |
| Quality | Excellent |

---

*This preview was generated by md-beautify.*
`;

  try {
    const outputFile = options.output || `${themeName}-theme-preview.html`;
    
    // 转换markdown为HTML
    const htmlContent = markdownParser.render(sampleMarkdown);
    
    // 生成完整的HTML文档
    const fullHtml = generateFullHtml(htmlContent, { theme: themeName, inline: true });
    
    // 确保输出目录存在
    const outputDir = path.dirname(path.resolve(outputFile));
    ensureDir(outputDir);
    
    // 写入文件
    await fs.promises.writeFile(outputFile, fullHtml, 'utf8');
    
    logSuccess(`Theme preview generated: ${chalk.yellow(path.resolve(outputFile))}`);
    console.log(chalk.gray(`Open the file in your browser to see the ${themeName} theme preview.`));
    
  } catch (error) {
    logError(`Failed to generate theme preview: ${error.message}`);
  }
}

/**
 * 生成完整的HTML文档
 * @param {string} htmlContent 
 * @param {Object} options 
 * @returns {string}
 */
function generateFullHtml(htmlContent, options) {
  const theme = options.theme || 'default';
  const inline = options.inline;
  
  // 读取CSS文件
  const cssPath = path.resolve(process.cwd(), 'src/md-beautify.css');
  const customCssPath = path.resolve(process.cwd(), 'src/custom.css');
  
  let styles = '';
  
  if (inline) {
    // 内联样式模式
    try {
      if (fileExists(cssPath)) {
        styles += fs.readFileSync(cssPath, 'utf8');
      }
      if (fileExists(customCssPath)) {
        styles += fs.readFileSync(customCssPath, 'utf8');
      }
    } catch (error) {
      console.warn(`Could not read CSS files: ${error.message}`);
    }
  }
  
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Theme Preview - ${theme}</title>
  ${inline ? `<style>${styles}</style>` : ''}
</head>
<body>
  <div class="markdown-body">
    ${htmlContent}
  </div>
</body>
</html>`;
}